spring:
  application:
    name: expense-manager
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:expensedb;MODE=DB2
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
server:
  servlet:
    context-path: /expense-service

management:
  endpoints:
    web:
      exposure:
        include: health, info
